services:
  - type: web
    name: resume-analyzer
    env: python
    plan: free
    buildCommand: |
      pip install -U pip setuptools wheel
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    healthCheckPath: /health
    autoDeploy: true
